### ISSUE TITLE
Wayland WM detection

### ISSUE THREAD

**Issue by Gobidev** [Gobidev/pfetch-rs#1]
`pfetch-rs` uses [libmacchina](https://github.com/Macchina-CLI/libmacchina) for window manager detection, which currently relies on `wmctrl` being installed and the user running X11. I added detection with `xprop` in https://github.com/Macchina-CLI/libmacchina/commit/8f94e1f68ec860155e4087b634e97426f1f2a593 ~, but there was no new release since then.~ This ~also~ does not fix detection on Wayland

**Comment by Gobidev** [comment]
Related PR: https://github.com/Macchina-CLI/libmacchina/pull/164

**Comment by cd-CreepArghhh** [comment]
Is there any reason for this issue to still be open? From what I can tell this works, or at least with well known ones like Sway and Hyprland (I only tested on these two).

**Comment by Gobidev** [comment]
Added in https://github.com/Macchina-CLI/libmacchina/pull/164/ and 55991bceeec0eba5b95bc7272f41f6a1ac8a6bdc

**Comment by Un1q32** [comment]
I run hyprland so I can test for you when this is added

**Comment by Gobidev** [comment]
> I run hyprland so I can test for you when this is added

It should already work since version 2.8.1, I just forgot to close this issue. You can try it out like this:
```sh
PF_INFO="ascii title os host uptime pkgs memory shell editor wm de palette" pfetch
```

**Comment by Un1q32** [comment]
wm and de both work

**Comment by cd-CreepArghhh** [comment]
> I run hyprland so I can test for you when this is added

Oh I had already tested this with practically every wayland WM and DE I had installed (Hyprland, Sway, Plasma 6, GNOME, Wayfire, COSMIC Epoch, Cinnamon (Wayland Experimental) and a couple others) before editing my comment.
