### ISSUE TITLE
Feat: Homebrew package

### ISSUE THREAD

**Issue by 21st-centuryman** [Gobidev/pfetch-rs#14]
This will act as a little log/discussion for now for the attempts made to make this package part of Homebrew's core package.

Currently the repository needs to be 30 or more days before it is added to Homebrew-core, which it is yet to reach.

In the mean time if you'd like to try this package through homebrew, I have made it part of my personal tap:

```sh
brew install 21stcenturyman/homebrew-21st/pfetch-rs
```
or
```sh
brew tap 21stcenturyman/homebrew-21st
brew install pfetch-rs
```

**Comment by 21st-centuryman** [comment]
https://github.com/Homebrew/homebrew-core/pull/125807

**Comment by 21st-centuryman** [comment]
The PR has been published! 🎉🍻

This will most likely be able to be downloaded soon enough.

@Gobidev Great job on this project. Now more people have access to it. I will update the README as soon as I am able to install it using the cli.

**Comment by Gobidev** [comment]
Thank's a lot @21st-centuryman!
