### ISSUE TITLE
bedrock linux isn't detected

### ISSUE THREAD

**Issue by nyeta** [Gobidev/pfetch-rs#17]
running the pfetch-rs on bedrock linux shows only the stratum (the distribution running on top of bedrock) it's running from.
looking at the source code i see no mention of bedrock, bedrock needs to be handled specially since it isn't a distro but meta distro allowing to run other distros on top of it.
the original pfetch does detect bedrock by checking if PATH env contains "/bedrock/cross/", ~~i guess just checking if that something like "/bedrock/etc/os-release" exists would also be sufficient~~, nevermind that would still show bedrock even with strat -r option (hiding the bedrock from enviroment)

**Comment by Gobidev** [comment]
Thank you for reporting this, I will probably copy the detection method of the original pfetch unless I find something better.
