### ISSUE TITLE
Metrics wrong in readme

### ISSUE THREAD

**Issue by cpw2n5** [Gobidev/pfetch-rs#18]
In the first line of the benchmark table, the mean is larger than the min and the max, and the max is smaller than the min.

https://github.com/Gobidev/pfetch-rs/blame/main/README.md#L62

**Comment by Gobidev** [comment]
Oh, I must have messed something up there😅
I wanted to re-run the benchmark anyways since the performance has probably changed since v0.1

**Comment by Gobidev** [comment]
Fixed in 6834bfe7b56c431c543a52b0ef18e9a1c9729d7b
