### ISSUE TITLE
SteamOS ASCII

### ISSUE THREAD

**Issue by OldWorldOrdr** [Gobidev/pfetch-rs#19]
Would be nice to have an ASCII logo on my Steam Deck besides the tux

**Comment by Gobidev** [comment]
I tried making one, what do you think of this?
![image](https://user-images.githubusercontent.com/50576978/226144219-13cce63d-a103-4cd0-8333-cfe587584164.png)

**Comment by OldWorldOrdr** [comment]
awesome!

**Comment by Gobidev** [comment]
![image](https://user-images.githubusercontent.com/50576978/226183510-643986d2-a62e-46ff-8fe3-8d5f116cc715.png)

I added some colors, is this good or should I leave it white?

The actual SteamOS logo looks like this:
![image](https://imgs.search.brave.com/70aYFN4SuWkvntEzWe1_m39NTj9Bs7xSfBJ6t2qXfdM/rs:fit:1200:1080:1/g:ce/aHR0cHM6Ly9pMS53/cC5jb20vd3d3LnBl/bGlrYWlzdGEuZmkv/d3AtY29udGVudC91/cGxvYWRzLzIwMTQv/MDgvU3RlYW1PUy1M/b2dvLTEucG5nP3Nz/bD0x)

**Comment by OldWorldOrdr** [comment]
purple is definitely better

**Comment by OldWorldOrdr** [comment]
![Screenshot from 2023-03-19 10-52-23](https://user-images.githubusercontent.com/57970114/226184065-8fc242c9-75f3-4e36-8ba0-aa06e3fcb8d9.png)
heres the neofetch SteamOS logo for reference (taken from https://github.com/hykilpikonna/hyfetch)

**Comment by Gobidev** [comment]
Ok, thank you for your feedback :) I will leave it as is then

**Comment by OldWorldOrdr** [comment]
the only improvement I would make is to try and make it smaller, but idk how you would even do that, or if its possible without making compromises.

**Comment by Gobidev** [comment]
Yea it would be nice if it would be smaller, but I think this is pretty much the minimum to not lose too much detail. If you enable more pfetch output, it looks pretty good at its current size:
![image](https://user-images.githubusercontent.com/50576978/226184326-13afc729-d181-492f-a2d3-cfecbac394d3.png)
