### ISSUE TITLE
Vanilla OS Logo

### ISSUE THREAD

**Issue by IntoTheVoid-900** [Gobidev/pfetch-rs#21]
Here is the (full sized) logo in Neowofetch
![image](https://user-images.githubusercontent.com/74509183/226830148-155df5fe-d499-4891-a8dc-07eadf41cd0c.png)

**Comment by Gobidev** [comment]
I made two variants, a bigger one with more detail, and a smaller one that better fits the size of pfetch but with less details. Let me know what you think, the progress can be found at #22.

![image](https://user-images.githubusercontent.com/50576978/226902982-83e67aa2-cbbb-469b-95f1-24e7712c8c72.png)

![image](https://user-images.githubusercontent.com/50576978/226904961-cd12b87b-2fa7-42d0-8b9e-0e9977aed5a1.png)

**Comment by MonsterObserver** [comment]
> I made two variants, a bigger one with more detail, and a smaller one that better fits the size of pfetch but with less details. Let me know what you think, the progress can be found at #22.
> 
> ![image](https://user-images.githubusercontent.com/50576978/226902982-83e67aa2-cbbb-469b-95f1-24e7712c8c72.png)
> 
> ![image](https://user-images.githubusercontent.com/50576978/226904961-cd12b87b-2fa7-42d0-8b9e-0e9977aed5a1.png)

I really like it!

**Comment by Gobidev** [comment]
Thanks for the feedback, I will merge the small variant into main
