### ISSUE TITLE
Host and OS not correctly detected on macOS

### ISSUE THREAD

**Issue by OldWorldOrdr** [Gobidev/pfetch-rs#3]

**Comment by Gobidev** [comment]
MacOS is already supported (with a few issues, see #4). You can install it by installing `cargo` from https://rustup.rs/ and then running `cargo install pfetch`, or wait a bit for binary releases.

**Comment by OldWorldOrdr** [comment]
yeah but theres no apple logo lol

**Comment by Gobidev** [comment]
There is, you can get it with `PF_ASCII=macos pfetch`

**Comment by OldWorldOrdr** [comment]
on big sur at least i get the generic tux

**Comment by Gobidev** [comment]
Have you updated to v0.1.1?

**Comment by OldWorldOrdr** [comment]
> Have you updated to v0.1.1?

i made this issue right after i ran `cargo install pfetch` and tested it and saw the generic tux

**Comment by OldWorldOrdr** [comment]
i now get an apple on 1.1

**Comment by OldWorldOrdr** [comment]
<img width="1280" alt="Screen Shot 2023-02-17 at 10 05 10 PM" src="https://user-images.githubusercontent.com/57970114/219828511-1a9f8bf1-e2ad-48e7-8a39-92ffaf4772a5.png">

it doesnt correctly show the os or host

**Comment by OldWorldOrdr** [comment]
mine doesn't have a different title color since i added the option to disable it in my fork

**Comment by Gobidev** [comment]
Thank you for reporting this, I will look into it.

**Comment by OldWorldOrdr** [comment]
if you're looking for new features to stand out from the original pfetch, feel free to steal features from my fork, its a bit fucked up with packages on some systems not showing up if run through bash (likely a bash bug since dash and zsh work fine) but theres some cool stuff in there like a dedicated config file and the previously mentioned option to use the same color for the title as the rest of the text.

**Comment by Gobidev** [comment]
Fixed in 40ed953f9758b9aca9f21617dac0b578ec79b894
