### ISSUE TITLE
Colors are darker on Windows Terminal

### ISSUE THREAD

**Issue by OldWorldOrdr** [Gobidev/pfetch-rs#30]
IIRC some terminals treat bold text as always being bright, so I assume this is a result of the text not being bold in pfetch-rs

![Screenshot (24)](https://github.com/Gobidev/pfetch-rs/assets/57970114/85e07ac0-adcd-4ed6-81f0-374504bb4a09)

ignore the title that's a result of `PF_COL3="COL1"` not being supported in the original pfetch

**Comment by Gobidev** [comment]
Thank you @RubixDev for fixing this. It looks like it is a problem with Windows Terminal, which interprets `\x1b[36m` and `\x1b[38;5;6m` differently, while they are meant to look the same. #31 fixes this by using the same syntax as the original pfetch for colors below 8.
