### ISSUE TITLE
macOS Sonoma shows up as "Unknown"

### ISSUE THREAD

**Issue by OldWorldOrdr** [Gobidev/pfetch-rs#35]
<img width="319" alt="Screenshot 2023-10-05 at 9 33 54 AM" src="https://github.com/Gobidev/pfetch-rs/assets/57970114/570a2e24-1c12-421c-bd7e-f0243b0e7518">

**Comment by Gobidev** [comment]
This has already been implemented in https://github.com/Macchina-CLI/libmacchina/pull/163, so it will be fixed with the next `libmacchina` release.

**Comment by OldWorldOrdr** [comment]
libmacchina had a release btw

**Comment by Gobidev** [comment]
Thanks for the info, I somehow didn't get a notification
