### ISSUE TITLE
Add bazzite logo

### ISSUE THREAD

**Issue by noahdotpy** [Gobidev/pfetch-rs#38]
[Bazzite](https://bazzite.gg) is a custom image based on [Fedora Silverblue](https://fedoraproject.org/silverblue/) and [Universal Blue](https://universal-blue.org/) made to be a replacement for SteamOS on the [Steam Deck](https://www.steamdeck.com/).

The logo would want to look something the logos in the [directory](https://github.com/ublue-os/bazzite/tree/ee90e790a24043caf1e3bd2a54902467c856d093/system_files/shared/usr/share/ublue-os/bazzite) in the ublue-os/bazzite repo
* `logo.txt` is the neofetch ascii art
* `logo.svg` is what you want the logo to look like

**Comment by Gobidev** [comment]
I created a logo, this is what it looks like:
![pfetch-bazzite](https://github.com/Gobidev/pfetch-rs/assets/50576978/14e2ef62-1785-4298-88a5-7afd28431388)

The progress can be found at #39. Let me know what you think :)

**Comment by Gobidev** [comment]
@nicknamenamenick @noahdotpy added in 2.9.0 :)

**Comment by nicknamenamenick** [comment]
> @nicknamenamenick @noahdotpy added in 2.9.0 :)

Thanks!
