### ISSUE TITLE
ASCII not detected on MacOS

### ISSUE THREAD

**Issue by RancidCrab55** [Gobidev/pfetch-rs#4]
running pfetch on my M1 Mac
~~~
uname -mrv
22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000 arm64
~~~
results in the following output:
~~~
    ___      USER@HOSTNAME
   (.. |     host   arm64
   (<> |     kernel 22.3.0
  / __  \    uptime 3d 18h 55m
 ( /  \ /|   pkgs   0
_/\ __)/_)   memory 15441M / 32768M
\/-____\/
~~~

when i manually set `PF_ASCII` to "macos" it gives the correct ascii logo for MacOS
also `pkgs` should probably track brew by default.

**Comment by Gobidev** [comment]
The ASCII detection should be fixed in e92fba8d8d0cc05db448798a3a911795f74be86f, I will make a separate issue for the package count
