### ISSUE TITLE
Windows: Can't download binary

### ISSUE THREAD

**Issue by s0me1newithhand7s** [Gobidev/pfetch-rs#44]
Currently running win 11 23H2:
![image](https://github.com/Gobidev/pfetch-rs/assets/117505144/49dc2103-e75b-4f95-ba71-2ed469617681)

no matter how I've tried same "Virus detected" error appears on every browser I use:
![image](https://github.com/Gobidev/pfetch-rs/assets/117505144/94f7865f-7671-4900-936e-27d2abe39555)

yes, even tried download on my VPS, local server and even CasaOS host:
![image](https://github.com/Gobidev/pfetch-rs/assets/117505144/e576d3bd-4196-4ee7-b2f6-4bd5714682d5)

any idea why?

**Comment by Gobidev** [comment]
That's interesting. I tried to replicate your issue in a Windows VM and got a warning by Windows Defender but was able to download and execute the binary. Please check if your binary matches these checksums:
```
sha256: 77c886b572c6955c6f140bfba08164a665fb02e352645d798a682cea68835387
sha512: b6c23f73499fe5c3184679be91c06427168e55a2bda66eb9ea6bf89cf879f43005d9ed5ac336f1cf84f34eedad4431ad1a8a57645da671f5acbc209fa81b94b3
blake2: f2df3373814ea331c47e255b165b45cf78535fc323f70ad86d599385cb98e7a7073d44260efddb1becb2ea2d0615237c82c872a881b2935c33fba8b7db024820
```

If not, something on your network or computer must have modified the binary. I should probably add checksums to future releases for that reason.

If, however, the checksums do match, you could try to [submit the file for analysis](https://www.microsoft.com/en-us/wdsi/filesubmission/) to get it whitelisted.

Although I have not read through the sourcecode of every dependency of this project, I can assure you that the binary in the Github release does not contain any malware. You can also check the [VirusTotal scan here](https://www.virustotal.com/gui/file/77c886b572c6955c6f140bfba08164a665fb02e352645d798a682cea68835387).

**Comment by s0me1newithhand7s** [comment]
i know that pfetch-rs not a malware, bc i've used it on my linux machines, and windows VMs. 
also i've tried to install older version and got: 
![image](https://github.com/Gobidev/pfetch-rs/assets/117505144/682d4040-72de-49d3-aa09-7430fb16ce10)
(and sorry for late answer, i was busy working on my nixos config);

about checksums - i can't even pass moment of saving binary, due of this error. i think this is weird MS Defender behavior, so i'll try on my windows VM (where Defender is offed by regedit.exe) and report results.

**Comment by s0me1newithhand7s** [comment]
hello again, i'm with news:
after some testing i came to conclusion that this is massive Defender Issue, bc like 30-50% of binaries on github and gitlab is "virus detected" and cannot be downloaded and executed. at least - all new versions. 
as you can see on my sceernshot currently i'm using binary of alacritty on Windows, even this binary have same "virus detected" error.

2 things i can recommend if there is will be new issues like this:
1. Get rid of MS Defender any possible way.
2. If this no the case - use older versions, they works just fine, and i have no idea why.

i'll close issue bc solution for me have founded, and i hope - for others too. thank you for helping!
