### ISSUE TITLE
Update all logos

### ISSUE THREAD

**Issue by walking-octopus** [Gobidev/pfetch-rs#47]
It seems a lot of the logos have fallen out of date... Since the original pfetch is now dead along with neofetch, I think it's time to make one last pull.

In particular, I've noticed the Fedora logo is different between latest pfetch and pfetch-rs.

pfetch-rs v2.9.1

**Comment by Gobidev** [comment]
The original pfetch has been inactive for three years now, that was one of the reasons I started this project.
I am not sure which out-of-date logos you mean, some logos have been updated from the original pfetch (pop os and gnu hurd) and many more have been added, but the Fedora logo looks the same as it does in the latest  pfetch:
![https://raw.githubusercontent.com/Gobidev/pfetch-rs/f0dd09aa324b086ef561af2d6b53bf80f8d93e18/assets/logos/fedora.svg](https://raw.githubusercontent.com/Gobidev/pfetch-rs/f0dd09aa324b086ef561af2d6b53bf80f8d93e18/assets/logos/fedora.svg)

which is still representative of the current Fedora logo:

![[fedora](https://fedoraproject.org/w/uploads/2/2d/Logo_fedoralogo.png)](https://fedoraproject.org/w/uploads/2/2d/Logo_fedoralogo.png)

I am closing this for now, let me know if there are specific logos you want to see added or updated.

**Comment by walking-octopus** [comment]
Oh... Sorry for bothering you. While migrating my user packages from Brew to Nix, I accidentally downloaded `pfetch` instead of `pfetch-rs`, and saw the logo to be in a slightly different style. I mistakenly assumed other logos may have been out of date from the upstream too. I've attached a screenshot for context.

![Screenshot_20240505_131021](https://github.com/Gobidev/pfetch-rs/assets/46994949/861aa0ba-e708-46ea-b89e-f39a51fde9df)

Also, it does seem like there's a slight discrepancy between package counts. It's not a critical issue, and I understand for some managers, retrieval can be an expansive operation, so it may not be worth the time adding a cache just for this edge case.

Thank you for writing and maintaining this project. As I've myself come to understand, it can be challenging to stay on top of things as a maintainer. I hope I haven't added any more weight with this issue.

**Comment by Gobidev** [comment]
> I hope I haven't added any more weight with this issue.

No worries :)
