### ISSUE TITLE
slow on alpine Linux

### ISSUE THREAD

**Issue by qaqland** [Gobidev/pfetch-rs#48]
I test both pfetch-bash and pfetch-rs, the former takes 1.01s and the latter is 1.00s

it looks like getting the count of apk is very slow

Alpine Linux 3.19.1 x86-64

**Comment by qaqland** [comment]
use unstable interface is faster

```bash
grep '^$' /lib/apk/db/installed | wc -l
```

**Comment by Gobidev** [comment]
Thank you for reporting this, the faster method is now implemented in libmacchina 7.2.3 and pfetch-rs 2.9.2.

**Comment by qaqland** [comment]
looks good😎

```
qaq@lab ~/p/t/x86_64> time pfetch
   /\ /\       qaq@lab
  // \  \      os     Alpine Linux 3.20.0
 //   \  \     host   NUC11ATKC4 M68769-300
///    \  \    kernel 6.6.32-0-lts
//      \  \   uptime 1d 20h 27m
         \     pkgs   924
               memory 1235M / 15745M


________________________________________________________
Executed in   16.91 millis    fish           external
   usr time   10.70 millis  752.00 micros    9.95 millis
   sys time    6.32 millis  130.00 micros    6.19 millis

```

**Comment by qaqland** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/67083

after merge, is could be install by `apk add pfetch-rs`
