### ISSUE TITLE
Different colored text from the shell version of pfetch

### ISSUE THREAD

**Issue by Un1q32** [Gobidev/pfetch-rs#49]
top: pfetch
bottom: pfetch-rs

![image](https://github.com/Gobidev/pfetch-rs/assets/57970114/1a09d4c5-8609-4767-9562-a08fe087cb6f)

**Comment by Gobidev** [comment]
The color management in the original pfetch was a bit buggy, the colors in this project are correct. If you want a different color you can overwrite the logo using `PF_CUSTOM_LOGOS` and changing this number:
```
        read_ascii 6 <<-EOF
```

**Comment by Un1q32** [comment]
Oh, actually the number was just different in pfetch and pfetch-rs, not sure how that happened, probobly my fault since I contributed that icon.
