### ISSUE TITLE
CachyOS logo

### ISSUE THREAD

**Issue by aspizu** [Gobidev/pfetch-rs#54]
Add the logo for [https://cachyos.org/](https://cachyos.org/) please.

**Comment by Gobidev** [comment]
I created a logo in the [cachyos branch](https://github.com/Gobidev/pfetch-rs/tree/cachyos), it looks like this:
![](https://raw.githubusercontent.com/Gobidev/pfetch-rs/800fd585b8891558a3b1102186ba26dfb9a8b829/assets/logos/cachyos.svg)

You can also find it [here](https://github.com/Gobidev/pfetch-rs/blob/800fd585b8891558a3b1102186ba26dfb9a8b829/all_logos.md).

Any feedback is welcome :)

**Comment by aspizu** [comment]
lgtm, thanks
