### ISSUE TITLE
Update the AUR pkgbuild to also conflict with "pfetch" as it does

### ISSUE THREAD

**Issue by Rishabh672003** [Gobidev/pfetch-rs#8]

**Comment by Gobidev** [comment]
Fixed in [20b426d0422ca387796403f8c53868422a3e4644](https://aur.archlinux.org/cgit/aur.git/commit/?h=pfetch-rs-bin&id=20b426d0422ca387796403f8c53868422a3e4644)

**Comment by Rishabh672003** [comment]
thanks
