### ISSUE TITLE
Embed the logos in the binary

### ISSUE THREAD

**Issue by TheHolyTachanka** [Gobidev/pfetch-rs#9]
Im not that experienced in rust but wouldnt it be better to embed the strings in the binary with `include_str!`
something like this
```rs
const ARCH = include_str!(#"
				       /\\
				      /  \\
				     /\\   \\
				    /      \\
			           /   ,,   \\
				  /   |  |  -\\
				 /_-''    ''-_\\"#);
const ARCO = include_str!(#" 
				      /\\
				     /  \\
				    / /\\ \\
				   / /  \\ \\
				  / /    \\ \\
				 / / _____\\ \\
				/_/  \`----.\\_\\"#);

match distro {
     "arch" => ARCH,
     "arco" => ARCO
};
```
(I wrote this in github's editor ignore any mistakes in the code)

**Comment by Gobidev** [comment]
The logos are embedded in the binary, using a Rust proc-macro (pfetch-extractor). It reads the logos from the logos.sh file at compile time and includes them in the binary. This makes it easy to port modifications to the original logos over to this project.

**Comment by TheHolyTachanka** [comment]
> The logos are embedded in the binary, using a Rust proc-macro (pfetch-extractor). It reads the logos from the logos.sh file at compile time and includes them in the binary. This makes it easy to port modifications to the original logos over to this project.

K then srry for the issue

**Comment by Gobidev** [comment]
no worries^^
